# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48e80bc8fa70e77eb9aaff20d44170a5c0dce6c5915aaf3a8e0d7967dab755e2590906a7083fa5ab27afce6f3ddbde4a56b83af4c9b837b525d94ee58ed3ae9
  fyber_app_id: <%= ENV["FYBER_APP_ID"] %>
  fyber_device_id: <%= ENV["FYBER_DEVICE_ID"] %>
  fyber_locale: <%= ENV["FYBER_LOCALE"] %>
  fyber_ip: <%= ENV["FYBER_IP"] %>
  fyber_offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
  fyber_api_key: <%= ENV["FYBER_API_KEY"] %>


test:
  secret_key_base: 58fb07874293b65eaaa7faeb57a9d8c064c85dac8a805d92604d1ec81fdea3ee9496ca7129995f22ad4e521dd324d27b9f003fd43cf1513fc409d31fd07b65cf
  fyber_app_id: <%= ENV["FYBER_APP_ID"] %>
  fyber_device_id: <%= ENV["FYBER_DEVICE_ID"] %>
  fyber_locale: <%= ENV["FYBER_LOCALE"] %>
  fyber_ip: <%= ENV["FYBER_IP"] %>
  fyber_offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
  fyber_api_key: <%= ENV["FYBER_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fyber_app_id: <%= ENV["FYBER_APP_ID"] %>
  fyber_device_id: <%= ENV["FYBER_DEVICE_ID"] %>
  fyber_locale: <%= ENV["FYBER_LOCALE"] %>
  fyber_ip: <%= ENV["FYBER_IP"] %>
  fyber_offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
  fyber_api_key: <%= ENV["FYBER_API_KEY"] %>
